channable/vaultenv

- README.md
A nice shortcut to running the built binary.
Great project btw! Very similar to a GPG-based tool we use internally that we hadn't expanded to out Vault usage yet. This works very well.
> Mention `stack exec`

- README.md
- app/Main.hs
Fixes #14 
I named the new config option `no-env-inheritance` but ready to change it if anyone has a better alternative.
PS: this PR and https://github.com/channable/vaultenv/pull/19 will cause merge conflicts
> Disable environment inheritance config option

- app/Main.hs
- integration-test.sh
Fixes #5 
In the issue the options mentioned are failing or printing a warning: I leaned towards the former since overriding a variable name is most of the times something done by accident in my experience. But let me know what you folks think about it, if you have a different opinion it won't take much work to change the PR.
The time complexity of `dups` is still quadratic but since that wasn't seen as a performance issue before I didn't use a better one.
> Fail if duplicate environment variables are found

- app/Main.hs
- integration-test.sh
- package.yaml
Now, only one request is send even when multiple keys from a secret are
requested. See discussion of issue #18.
> Make vaultenv only send one request per secret

- package/deb_control
I've faced with issue running vaultenv in Docker containers, on official Ubuntu images. The error was:
```
vaultenv: [ERROR] Network trouble. Host can be unreachable, requests may be timing out or DNS not working.
```
The file `/etc/protocols` is absent in image, and it providing by `netbase` package. I think it would nice to have this package in dependencies. 
Strace output:
```
[pid   486] open("/etc/protocols", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   486] write(22, "\1\0\0\0\0\0\0\0", 8) = 8
[pid   485] <... poll resumed> )        = 1 ([{fd=22, revents=POLLIN}])
[pid   485] read(22,  <unfinished ...>
[pid   486] getrusage(RUSAGE_SELF,  <unfinished ...>
[pid   485] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid   486] <... getrusage resumed> {ru_utime={0, …
```
> Added netbase package

- README.md
- app/Main.hs
Makes the base delay for the vault exponential backoff reconnection
strategy configurable, as requested in #11.
> Option for retry-base-delay

- app/Main.hs
- package.yaml
- stack.yaml
This PR adds a new CLI option `--no-validate-certs` to vaultenv. It addresses #34 
Still needs an integration test, but I have verified this locally
> Add option to skip cert validation

- app/Main.hs
- package.yaml
- src/Config.hs
This PR allows us to configure `vaultenv` using environment variables (fixes #28). We support setting the following options:
- `--host`
- `--port`
- `--token`
- `--secrets-file`
- `--[no-]connect-tls`
- `--[no-]validate-certs`
- `--[no-]inherit-env`
- `--retry-base-delay-milliseconds`
- `--retry-attempts`
Notes:
- The first three are named after the corresponding variables which can be used to configure the official `vault` CLI: `VAULT_HOST`, `VAULT_PORT`, and `VAULT_TOKEN`. 
- The others are prefixed with `VAULTENV`. 
- The options which disable defaults are named `VAULTENV_NO_*`, because they explicitly disable the default behavior.
- CLI arguments take precedence over environment variables.
- Boolean settings are parsed from the strings `"true"` and `"false"`. No other formats are …
> Configuration via environment variables

- README.md
- app/Main.hs
- src/Config.hs
This fixes a small bug/ergonomics issue where strings passed via environment variables needed to be in Haskell format. From now on, we just use the plain string.
This means users can provide strings like so:
$ VAULT_HOST="vault.company.com" vaultenv ...
Instead of having to provide them as a Haskell value:
$ VAULT_HOST='"vault.company.con"' vaultenv ...
This isn't a backwards incompatible change, since the previous behavior never made it into a release.
> Parse bug for string environment variables

- README.md
- app/Main.hs
- src/Config.hs
During #38, we introduced new environment variables through which we allow configuring `vaultenv`. They were named a bit poorly, though. I named them after the option `--no-connect-tls`, which was introduced earlier. This was not the best idea.
This PR fixes that potential papercut by renaming these environment variables to something better. While doing this, I also noticed that the "debug" option would be better if it was called LogLevel.  This is just better naming than "debug on" and "debug off", and also allows for future expansion if we need it.
> Remove double negative from configuration

- package.yaml
`vaultenv` does not use threads, and asynchronous IO is also provided by the
single threaded RTS. Secrets can therefore still be fetched in parallel.
In a quick test, this also appears to be faster than using the threaded RTS.
> Use single threaded GHC RTS

- app/Main.hs
- src/Config.hs
Before this patch, Vaultenv used to require an absolute path to the executable it launches. This is a good default for when you use Vaultenv for systemd services.
In local development, however, this is too limiting. Especially if you want to use vaultenv to fetch secrets to fetch for use in local development. Then, PATH searching is a feature you want, because executables live in different locations from machine to machine.
This is a quick patch to add this option to Vaultenv. It introduces a new flag `--use-path`, which enables path search. This flag is turned off by default.
> Add option to search PATH

- README.md
- app/Main.hs
- package.yaml
- src/Config.hs
Fixes https://github.com/channable/vaultenv/issues/57
This is an enhancement to make `vaultenv` more useful on devmachines.
Currently users need to specify stuff like `--host`, `--port`, and `--token` manually (or create a wrapper script which does). This changes `vaultenv` to look for for files with the `.env` format in three places:
- `/etc/vaultenv.conf`
- `$HOME/.config/vaultenv/vaultenv.conf`
- `$(cwd)/.env`
New config file precedence in case of duplicate settings:
- `/etc/vaultenv.conf`
- `$HOME/.config/vaultenv/vaultenv.conf`
- `$(cwd)/.env`
- Env vars which are set
- CLI options
Later items in the list take precedence
> config: Search for config files in default places

- RELEASE.md
- src/Config.hs
This is the actual proper fix for https://github.com/channable/vaultenv/issues/52
I found out how to get short-circuiting behavior (I was afraid
this would require changes to the Config datatype), but apparently
optparse-applicative has something for this.
I also found out how you can get information on the program version
from the Cabal file, which means less duplication of this
information.
cc @mesaugat
> app: Add explicit --version command

- src/SecretsFile.hs
- test/golden/v1.secrets
- test/integration/happy_path.sh
- test/integration_test.sh
- test/invalid/wrong_envvar_names.secrets
This PR supersedes https://github.com/channable/vaultenv/pull/60 and fixes issues with the `vaultenv` parser being too strict about environment variable names
> Fix characters allowed in environment variables

- app/Main.hs
- package.yaml
- test/integration_test.sh
This is a WIP to fix #62 
I went with the "use heuristics" approach to this problem. The two formats are unambiguous, so we don't need any extra information specified by the user to approach this. Normally, I'd go for "explicit", but this approach means users can use `vaultenv` on a secret backend with the same secrets file before and after an upgrade.
Approach:
- Drop `lens` and `lens-aeson`. They didn't really make it easier than writing the instances by hand
- Add a `FromJSON` instance for `VaultData` (which is now `data` instead of `type`) that can parse both
Todo: integration test, agree on heuristic approach.
> Add support for key/value engine v2

- .travis.yml
Closes issues #67 # #61
This PR adds the integrations with travis-ci and executes the suite test for all branches when travis-ci detects that a new tag has been pushed runs` stack build `,  `stack test` and create a new release and uploads the binaries built for osx and Linux.
The format will be `vaultenv-v$version-$os`  (vaultenv-v0.9.1-osx) I tested forking the repo and trying by myself
To create the release, you will need to define two environment variables in travis-ci:
- A user that have permissions over the repo `$GITHUB_USER = lpaulmp`
- Generate a Github token with permissions over the repo `$GITHUB_TOKEN = mytoken1234`.
@duijf I hope you find this useful
> Add integration with travis-ci and publish binaries

- .travis.yml
I don't want spam for builds, especially not builds that pass. If anybody likes the failed build notifications we could change it to [`on_success: never`](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications) to still get mails for failed builds.
> Turn off Travis email notifications

- app/Main.hs
- package.yaml
- src/Config.hs
- test/ConfigSpec.hs
- test/integration/environment_inherritance.sh
- test/integration/invalid_addr.sh
Fixes #66.
Added support for VAULT_ADDR to the config files, as well as the command
line arguments. Changed the config parsing process such that everything
is parsed to an Options datatype after which the options are merged. The
addr field is after each separate parsing verified to be correct and the
information is distributed over the UseTLs (HTTP/HTTPS), Host and Port.
> Added addr support to vault

- src/SecretsFile.hs
- stack.yaml
- stack.yaml.lock
This upgrades to the new stack LTS. There were some breaking changes in megaparsec, which I've fixed now.
> stack: Update to LTS 14.7

- .gitignore
- README.md
- RELEASE.md
- default.nix
- nix/nixpkgs.nix
- nix/static-haskell-nix.nix
- nix/vaultenv-static.nix
- package.yaml
- src/Config.hs
- stack.yaml
Fixes https://github.com/channable/vaultenv/issues/43 (Well not for `0.7.1`, but from now on)
I managed to get a static binary build working for vaultenv! Huge thanks is in order to @nh2 for the `static-haskell-nix` project.
Approach:
- Import the default build script from static-haskell-nix and adjust
it for our use case.
- Rename vaultenv to vautlenv-real to work around the fact that nixpkgs
also contains vaultenv. This was causing conflicts. (There is
probably a better way to do this, but I didn't figure that out yet.
If someone reading this knows how we can work around this, we'd
appreciate any tips.)
- Tweak the documentation.
Possible downsides:
- This might break when we add new deps or upgrade to a new stackage snapshot. As `vaultenv` is updated infrequently, I think this is fine.
> Static binary

- README.md
- app/Main.hs
- src/Config.hs
- test/integration/inherit-env-blacklist-both.sh
- test/integration/inherit-env-blacklist-existing.sh
- test/integration/inherit-env-blacklist-secret.sh
This PR adds the option `--inherit-env-blacklist` to Vaultenv.
This option takes a comma-separated list of environment variable names, and when
defined these environment variables are removed from the environment before Vaultenv
executes the command to run.
This option does not implicitly enable `--inherit-env`, and the blacklist is not
applied if `--inherit-env` is `false` (we could change `buildEnv` so it does if this
is desired).
No warning is given if a variable defined in the secrets file is removed by this
blacklist.
Example usage:
```console
$ stack run -- --secrets-file /tmp/dummy-file env | grep VAULT_
VAULT_TOKEN=present-in-environment
VAULT_HOST=127.0.0.1
VAULT_PORT=8200
$ # Filter Vault token from environment
$ stack run -- --secrets-file /tmp/dummy-file …
```
> Add option to remove environment variables before executing program

- .gitignore
- README.md
- RELEASE.md
- default.nix
- package/build_package.sh
- package/deb_control
This PR brings back the scripts to build a .deb package for Vaultenv, after it was
removed in 9fb4125. The scripts have been altered to use the static binary built by
Nix, which means that we can publish the .deb without any dependencies and it should
work on any Debian / Ubuntu derivative.
> Build .deb package with static binary from Nix

- app/Main.hs
- package.yaml
- src/Config.hs
- src/SecretsFile.hs
- test/integration/retry_tests.py
- test/integration/tap.py
- test/integration_test.sh
This PR reworks the internal logic of Vaultenv to remove the use of the `ExceptT`
monad and fix the retrying logic for fetching both the mount information and the
secrets.
It was discovered that the existing retry code had no effect due to the `http`
library throwing IO exceptions, which were not caught by the ExceptT monad
combination we used. Additionally, the retries were not enabled on the first call to
the server for the secret store mount information.
In this PR the relevant functions that use the ExceptT construction are reworked or
replaced to return either `Either VaultError result` or `IO (Either VaultError
result)`, and `Retry.retrying` is used directly to retry when a network-related
`VaultError` is returned.
This PR also alters the handling for HttpExceptions to ensure that …
> Fix retry behavior

- package/build_package.sh
- package/deb_postinst
We've noticed an issue with the permissions of the file installed from the .deb
package which caused the installed binary and `/etc/secrets.d` to not be owned by
`root` but by the uid of the building user on the build machine.
This PR alters the packaging script to use `fakeroot` to ensure that the built
package includes files owned by `root` instead of some random user, without requiring
building the package as `root`.
It also adds a `postinst` script that will fix the permissions after upgrading from
an affected version of the package.
> Fix permission issue on .deb package

- package.yaml
- src/Config.hs
- test/ConfigSpec.hs
Fixes #94 
This implementation expands the String operations to get the job done. This works, but it feels rather fragile. Chances are, there are other valid URLs that are not accepted by the code. Perhaps in time it is better to use [parseRequest](https://hackage.haskell.org/package/http-client-0.7.0/docs/Network-HTTP-Client.html#v:parseRequest) or [parseURI](https://hackage.haskell.org/package/network-uri-2.6.3.0/docs/Network-URI.html#v:parseURI).
> Allow VAULT_ADDR addresses without ports

- app/Main.hs
- src/Config.hs
Vault Agent is a kind of local Vault proxy that can take care of authentication and caching, but it's better described by [its own documentation](https://www.vaultproject.io/docs/agent).
This PR makes Vaultenv easier to use with Vault agent, with two changes:
- The `Token` parameter is now optional, as it is not required when the Vault Agent provides auto authentication. If the parameter is not set, the relevant header is not added to the request. If the token turned out to be required after all, the Vault server will respond with a `BadRequest` informing you of that fact so it still fails fast.
- The `x-vault-request: true` header is added to every request. If Vault's SSRF protection is enabled, this header is required for requests to go through. Otherwise, it is silently ignored, just …
> Make vaultenv more friendly for use with Vault Agent

- default.nix
- nix/sources.json
- nix/stack-shell.nix
- nix/vaultenv-static.nix
- package.yaml
- stack-static-build.yaml
- stack.yaml
- vaultenv.nix
Fixes `build_package.sh`, that broke after https://github.com/channable/vaultenv/pull/98
This PR:
- Reverts the GHC version back to 8.6.5
- Uses the correct GHC version when using stack
- Allows building of static packages again, by using a separate `.yaml` file.
> Fix `build_package.sh`

- README.md
- app/Main.hs
- src/Config.hs
When there are a lot of secrets to be fetched, imposing a limit makes it
possible to reuse more connections to the vault server. This reduces the
load on the vault server because expensive TLS handshakes can be
avoided.
Closes https://github.com/channable/vaultenv/issues/106.
> Limit parallelism, enabling more connection reuse

- app/Main.hs
- nix/haskell-dependencies.nix
- nix/haskell-overlay.nix
- nix/nixpkgs-pinned.nix
- nix/overlay.nix
- nix/sources.json
- nix/sources.nix
- nix/stack-shell.nix
- nix/vaultenv-static.nix
- package.yaml
- src/KeyMap.hs
- stack.yaml
- test/KeyMapSpec.hs
XRef: https://github.com/channable/vaultenv/issues/118
This is the first try to overwrite the packages such that `stack` can compile with `aeson 2.0.*` available.
This adds a Haskell overlay in the process.
This overwrites the minimal set of packages in the `./nix/haskell-overlay.nix` to enable `aeson 2.0.*`.
---
The current state is that the dependencies compile but the package itself needs to be modified to work with the updated `aeson` package.
```
$ nix run -c stack build
vaultenv-real> build (lib + exe)
Preprocessing library for vaultenv-real-0.14.0..
Building library for vaultenv-real-0.14.0..
Preprocessing executable 'vaultenv' for vaultenv-real-0.14.0..
Building executable 'vaultenv' for vaultenv-real-0.14.0..
[1 of 2] Compiling Main [SecretsFile changed] …
```
>  Bump `aeson` from `1.5.*` to `2.0.*`

- default.nix
Removes cachix from default.nix
> Remove cachix from default.nix

- README.md
- RELEASE.md
This replaces references references to `nix run` (from Nix 2.3) to `nix shell` (used from Nix 2.4 and later).
> Replace references to nix run with nix shell

- app/Main.hs
I was trying to get things to run with the new Kubernetes authentication introduced in #122, but I ran into some issues. This additional logging helped me to diagnose the issue.
It’s a bit ugly to replicate the `getOptionsValue oLogLevel (cCliOptions context) <= Info`, maybe it makes sense write small function for this.
Off topic: the issue I was facing (writing this down here in case future visitors are facing the same issue). The policy associated with the role did not have permission to read `/sys/mounts`. Vaultenv did not fail on this when it requested the mounts, but it caused it to make a request to `/v1/secret/mypath` instead of `/v1/secret/data/mypath`. The additional logging helps diagnose this. The solution was to add
```hctl
path "sys/mounts" {
capabilities = ["read"]
}
```
to …
> Add a bit more logging at info level

- README.md
- app/Main.hs
- src/Config.hs
- test/integration/duplicate_env_var.sh
Fixes https://github.com/channable/vaultenv/issues/134
Allow us to overwrite the duplicate variables error with a new flag. When enabling this flag, we don't error on duplicate variables, but instead take the ones from the environment already specified.
> Allow overwriting over environment variables

- app/Main.hs
- nix/haskell-dependencies.nix
- package.yaml
Using http-client-openssl that also handle the SSL_CERT_FILE environment variable
refs #99
> Use http-client-openssl instead of http-client-tls

- README.md
- app/Main.hs
- default.nix
- nix/haskell-dependencies.nix
- nix/nixpkgs-pinned.nix
- nix/overlay.nix
- nix/sources.json
- nix/sources.nix
- nix/stack-shell.nix
- package.yaml
- stack.yaml
- test/default.nix
- vaultenv.nix
Seems like `crypton-connection` is superseding `connection`, and a large portion of the Haskell ecosystem has done the migration. Having both connection and crypton-connection in a project causes a conflict on the `tls` version.
Links:
- https://hackage.haskell.org/package/crypton-connection-0.3.1
- https://hackage.haskell.org/package/connection
> Nixpkgs update, and crypton-connection upgrade

- README.md
- src/Config.hs
has this ever happened to you?
```
$ vaultenv -- echo "hello"
[ERROR] The option Secret file is required but not specified
$ vaultenv --secret-file foo.secrets -- echo "hello"
Invalid option `--secret-file'
Usage: vaultenv [--version] [--host HOST] [--port PORT] [--addr ADDR] 
[--token TOKEN | --kubernetes-role ROLE | --github-token TOKEN] 
[--secrets-file FILENAME] [CMD] [ARGS...] 
[--no-connect-tls | --connect-tls] 
[--no-validate-certs | --validate-certs] 
[--no-inherit-env | --inherit-env] 
[--inherit-env-blacklist COMMA_SEPARATED_NAMES] 
[--retry-base-delay-milliseconds MILLISECONDS] 
[--retry-attempts NUM] [--log-level error | info] [--use-path] 
[--max-concurrent-requests NUM] 
[--duplicate-variable-behavior error | keep | overwrite]
```
i also took the liberty of improving the …
> Add an alias for '--secrets-file'
